---
version: "2"
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/config
      - smokeping-data:/data
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  smokeping-data:
    driver: local
